version: "1.0"

services:

  web-backend:
    build:
      context: ./project
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload  --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - "8004:8000"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test

  web-db:
    build:
      context: ./project
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USERS=postgres
      - POSTGRES_PASSWORD=postgres
